cmake_minimum_required(VERSION 3.16)
project(notifyAOP)
include(GNUInstallDirs)
include_directories(public)
find_package(PkgConfig)
# Get systemd unitdir from systemd's pkg config file
pkg_search_module(SYSTEMD REQUIRED "systemd")
pkg_search_module(LIBSYSTEMD REQUIRED "libsystemd")
pkg_get_variable(SYSTEMD_SYSTEM_UNIT_DIR systemd "systemdsystemunitdir")
add_executable(notify_aop notify_aop.c)
target_link_libraries (notify_aop lrmc)
target_link_libraries (notify_aop pm-client)
target_link_libraries(notify_aop PRIVATE ${GLIB_2_LDFLAGS})
target_compile_options(notify_aop PRIVATE ${GLIB_2_CFLAGS})
install(TARGETS notify_aop RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})
